apiVersion: v1
kind: Service
metadata:
  name: server1-service
  namespace: development
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: server1-deployment
  type: ClusterIP