apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server1-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server1-deployment
    spec:
      containers:
      - name: server1-container
        envFrom:
          - configMapRef:
              name: server1-config
        image: registry.hub.docker.com/pcamacho7/test-bp:HASH