name: staging CI
on:
  push:
    branches: [ main ]
jobs:
  # code taken from https://docs.github.com/es/actions/guides/building-and-testing-python
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ./app/test_server.py
    
  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the tagged Docker image
        run: docker build --compress --force-rm --rm --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }} .

      - name: Push the tagged Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }}

  deploy-on-k8s:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      SHA: ${{github.sha}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up gCloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Login GKE 
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Deploy services on Kubernetes
        run: |
          make deploy 